#include <iostream>

int main(){
    std::cout << "raldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslf   s fs f a sfas f af sas f kdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasjraldsfjaslfkdjsdkjfasj";
    std::cout << '\n';
}